#Definir des services app et db
services:
  app:
    build: . # Créer une image à partir du Dockerfile courant
    image: laravelapp
    #entrypoint: /bin/bash -c "php artisan migrate && php artisan serv --host 0.0.0.0"
    #entrypoint: /bin/bash /projet/entrypoint.sh
    #entrypoint: /projet/entrypoint.sh
    entrypoint: ["/bin/bash", "/projet/entrypoint.sh"]
    restart: unless-stopped
    ports:
      - "7000:8000"
    volumes:
        - ./app:/projet
    depends_on:
      - db


  db:
    image: postgres:15
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .db.env
      #- ./app/.env
    #environment:
     # - POSTGRES_USER=${DB_USERNAME}
      #- POSTGRES_DB=${DB_DATABASE}
      #- POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  dbdata:
